### ISSUE TITLE
Changing or disabling timeout for config reload?

### ISSUE THREAD

**Issue by analogic** [haraka/haraka-config#42]
I see there is 5 * 1000 timeout for reloading configs (https://github.com/haraka/haraka-config/blob/f501adc4d3a288d062e979c0b2fe86d202e5894c/configfile.js#L130) - I've written some integration tests and time adds up, is there any particular reason for such long time? Is it bad idea to switch off waiting entirely?

**Comment by msimerson** [comment]
The root issue was identified when I was working on a mail system that wrote out a rather large config file consisting of ~100,000 domains that the mail server was accepting mail for. Since it took a bit of time to write the file, Haraka would get a file change event well before the file was finished writing. Haraka would then re-read the partially written file with obvious negative effect.

I worked around that problem on that mail system by having the file written to disk as a tmp file, and then moving the temp file into place. We added the 5 second delay to prevent such an issue from harming other users.

If you're certain your use of Haraka won't be harmed by removing that, feel free to make the change locally. There's my be another way to solve the "detect that a file is no longer being written to, and thus safe to re-read" issue, but one hasn't sprung to mind.

**Comment by analogic** [comment]
@smfreegard yes, I am doing lot of tests - currently I restart node on every settings change, but it is not "cheap" nor time predictable on different setups. Simulate Haraka in production and test it with all feature set is almost impossible due lot of external variables, so I am ok with some kind of tweaking...

@msimerson Thanks, I thought it is some kind of protection. (I very much like "incron" which works similary and I know that it can get easily messed up)

 I am afraid that "detect that a file is no longer being written to" will not work on different platforms. I would like to contribute in some way, but the best solution I've come to was monkey patch this file to fit my need
